[features]
seeds = false
[programs.localnet]
sword_play = "AA91rmiK5gZBw1Gmdq75NBVwm7yeF67ti8T7PnwMNoZk"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/jake/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
